name: Gerar APK ErenTech

on:
  workflow_dispatch:

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v6

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Instalar SDK necessário
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Compilar APK
        run: |
          gradle --no-daemon assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: ErenTech-APK
          path: app/build/outputs/apk/debug/app-debug.apk
